---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'one-ring'
SiteConfig:
  extensions:
    - SiteConfigExtension

Security:
  token: 1bddcfc914469b7a2c6b0a63985b1831c3898b2a
