# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.6

env:
  - DB=MYSQL CORE_RELEASE=3.2

before_script:
  - phpenv rehash
  - composer self-update || true
  - git clone git://github.com/shoaibali/one_ring.git ~/builds/ss
  - cd ~/builds/ss
  - wget https://gist.githubusercontent.com/shoaibali/da42301538a4fe098653/raw/0209590124c917a3dd69d9b1a52bf5c83cf670f0/_ss_environment.php
  - composer install

#Execute tests with or without coverage
script:
  # Execute tests with no coverage.  This is the fastest option
  - phpunit mysite/tests/
